version: '3'
services:
    web:
        build: .
        volumes:
            - ".:/usr/app"
        ports:
            - "8010:80"
        environment:
            - DATABASE_URL=postgres://fooddude:12345@postgres/fooderator
        restart: always
        depends_on:
            - postgres
        command:
            - nodemon
    postgres:
        image: postgres:9.6.6-alpine
        environment:
            - POSTGRES_USER=fooddude
            - POSTGRES_PASSWORD=12345
            - POSTGRES_DB=fooderator
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data:
        external: true