version: '3'
services:
    web:
        build: .
        volumes:
            - ".:/usr/app"
        ports:
            - "8010:80"
        env_file:
            - ".env"
        environment:
            - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
        restart: always
        depends_on:
            - postgres
        command: ["nodemon", "-L"]
    postgres:
        image: postgres:9.6.6-alpine
        env_file:
            - ".env"
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data:
        external: true